# Robot Configuration
robot:
  base_frame: base_link_frd
  operation_frame: torso_link4

  # DOF limits for robot arms
  dof_limits:
    lower: [-3.1, -2.268, -3.1, -2.355, -3.1, -2.233, -6.28]
    upper: [3.1, 2.268, 3.1, 2.355, 3.1, 2.233, 6.28]

  # Hand configuration
  hands:
    left:
      ip: 192.168.3.210
      port: 6000
      read_service: /inspire_hand_modbus/get_angle_act
      move_service: /inspire_hand_modbus/set_angle
      default_open: [1000, 1000, 1000, 1000, 1000, 1000] #[1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      default_standby: [755, 805, 820, 860, 1000, 410]
      default_grasp: [525, 510, 495, 450, 500, 0] #[1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      default_speed: [200, 200, 200, 200, 200, 200]
      
    right:
      ip: 192.168.3.44
      port: 6000
      read_topic: /inspire_hand_modbus/get_angle_act
      move_topic: /inspire_hand_modbus/set_angle
      default_open: [1000, 1000, 1000, 1000, 1000, 1000] #[1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      default_standby: [755, 805, 820, 860, 1000, 250]
      default_grasp: [10, 150, 250, 450, 500, 0] #[200, 300, 400, 450, 500, 0]
      default_speed: [200, 200, 200, 200, 200, 200]
  # Arm configuration
  arms:
    left:
      ip: null
      read_topic: /hdas/feedback_arm_left
      read_ee_topic: /motion_control/pose_ee_arm_left
      move_topic: /motion_target/target_joint_state_arm_left
      move_ee_topic: /motion_target/target_pose_arm_left
      init_qpos: [-0.6, 0.6, -0.5, -1.3, 0, 0, 0] #[-0.10979866, -1.37397554, -1.11486395, -0.99602451, 0.28651326, -0.55909878, 0.59166664]
      # init_qpos: [-1.2, 0.9, -1.5, -1.2, 0.9, 0.16, -0.26]
      init_ee: [0.526, 0.3360, 0.12140, 0.1876, -0.7094, -0.320, 0.5989] #[position: x y z orientation: x y z w]
      default_qvel: [1, 1, 1, 1, 2, 2, 2]
    right:
      ip: null
      read_topic: /hdas/feedback_arm_right
      read_ee_topic: /motion_control/pose_ee_arm_right
      move_topic: /motion_target/target_joint_state_arm_right
      move_ee_topic: /motion_target/target_pose_arm_right
      init_qpos: [-0.6, -0.6, 0.5, -1.3, 1.3, 0, 0] #[0.36939895, -1.42726047, 0.32529447, -0.78829542, -1.78686804, 0.85681702, 2.33696087]
      # init_qpos: [-1.2, -0.9, 1.5, -1.2, 0.7, 0.16, -0.26]
      # init_qpos: [-1.166808510638298, -0.8778723404255319, 1.4831914893617022, -1.1734042553191488, 0.7246808510638297, 0.36148936170212764, -0.26170212765957446]
      init_ee: [0.526, -0.3360, 0.12140, -0.5780, -0.4510, 0.6181, 0.2833] #[position: x y z orientation: x y z w]
      default_qvel: [1, 1, 1, 1, 2, 2, 2]
      # placement_joint: [0.95171058, -1.10870292, 0.30105185, -1.85312083, -2.63649433, 0.25455627, 2.43874849]
      # placement_joint: [-1.3519148e+00, -6.0085094e-01,  1.4417024e+00, -1.2253193e+00, 1.2646809e+00, -3.6340427e-01, -5.7914877e-01]
      placement_joint:  [-1.1612766e+00, -6.6617024e-01,  1.4272342e+00, -1.4314893e+00, 1.4136167e+00, -1.3574481e-01, -5.3234053e-01]
      return_medium_joint: [0.58597687, -0.72916365, 0.20774654, -1.24625233, -2.82404745, 1.29088039, 2.68651541]
  torso:
    move_topic: /motion_target/target_joint_state_torso
    init_qpos: [0.3, -0.4, -0.5, 0]
    default_qvel: [0.25, 0.25, 0.25, 0.25]
# Camera Configuration
cameras:
  head_cameras:
    frame: "zed_link" # used to be zed_frame for pointcloud generated by zed itself
    topic: /hdas/camera_head/rgb/image_rect_color #/hdas/camera_head/rgb_raw/image_raw_color
    depth_topic: /hdas/camera_head/depth/depth_registered
    depth_info_topic: /hdas/camera_head/depth/camera_info
    pointcloud_topic: /hdas/camera_head/point_cloud/cloud_registered
    resolution: [640, 480]
  left_hand_cameras:
    topic: /hdas/camera_wrist_left/color/image_raw
    resolution: [640, 480]
  right_hand_cameras:
    topic: /hdas/camera_wrist_right/color/image_raw
    resolution: [640, 480]
# cameras:
#   right_first:
#     sn: null
#     resolution: [640, 480]
#   third:
#     sn: null
#     resolution: [640, 480]

# Model Configuration
sam:
  checkpoint: checkpoint/sam/sam_vit_h_4b8939.pth
  model_type: "vit_h"

# High Level Planner
planner:
  model_path_VL: "/data/yixiang/SRCB-DexVLA/checkpoint/Qwen2.5-VL-7B-Instruct"
  model_path_Omni: "/data/model/Qwen/Qwen2.5-Omni-7B"
# Logging Configuration
logging:
  path: "log/"
  exp_name: "demo"

# Control Parameters
control:
  arm_trajectory:
    interpolation_num: 20  # 轨迹插值点数
    position_error_threshold: 0.03  # 位置误差阈值
  monitor:
    max_episode_duration: 100  # 最大执行时间(秒)

# Visualization Configuration
visualization:
  bbox:
    color: [0.8, 0.2, 0.2]  # 边界框颜色 [R, G, B] 绿色
    linewidth: 2        # 边界框线宽
  mask:
    # color: [[0.1, 0.5, 1, 0.6]]  # 掩码颜色 [R, G, B, Alpha] 蓝色半透明
    color: [[0.1, 0.5, 1, 0.6],  # 掩码颜色 [R, G, B, Alpha] 蓝色半透明
            [0.95, 0.4, 0.5, 0.6],    # 珊瑚粉
            [0.3, 0.9, 0.7, 0.55],    # 薄荷绿
            [0.9, 0.7, 0.1, 0.65],   # 琥珀黄
            [0.7, 0.5, 0.9, 0.6],     # 薰衣草紫
            [0.9, 0.45, 0.1, 0.6],    # 氧化橙
            [0.2, 0.8, 0.8, 0.55],    # 青瓷色
            [0.8, 0.3, 0.6, 0.65],    # 玫瑰红
            [0.4, 0.4, 0.4, 0.5],     # 石板灰
            [0.5, 0.6, 0.2, 0.6],     # 橄榄绿
            [0.8, 0.2, 0.9, 0.55]]     # 电光紫